spring.application.name=housingaffordability
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional but recommended:
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true      
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Removing ASCII art from spring boot
spring.main.banner-mode=off

# Enable the use/trust of forwarded headers (like X-Forwarded-For) for Spring
# used to get the real client IP address when behind a reverse proxy
server.forward-headers-strategy=framework